# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:12-browsers
    - image: circleci/android:api-25-alpha
set_env: &set_env
  name: Setup Environment Variables
  command: |
    echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
    source $BASH_ENV
    echo "export CIRCLE_PR_BASE_SHA=`curl -s https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pulls/${CIRCLE_PR_NUMBER} | jq -r '.base.sha'`" >> $BASH_ENV
    echo 'export AFFECTED_ARGS="--base ${CIRCLE_PR_BASE_SHA}"' >> $BASH_ENV
    source $BASH_ENV
    echo $AFFECTED_ARGS
yarn_cache: &yarn_cache
  keys:
    - node-deps-node12-{{ checksum "package.json" }}
    # fallback to using the latest cache if no exact match is found
    - node-deps-node12-

yarn_install: &yarn_install
  name: Install Dependencies
  command: yarn install --non-interactive

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - run:
          <<: *yarn_install
      - save_cache:
          key: node-deps-node12-{{ checksum "package.json" }}
          paths:
            - ~/.cache
            - node_modules
 lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache 
      - run: ./node_modules/.bin/nx workspace-lint
      - run: yarn lint
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - run: yarn mobile:build
      - store_artifacts:
          path: /home/circleci/repo/
  e2e:
    <<: *defaults
    steps:
      - checkout
      - run:
          <<: *set_env
      - restore_cache:
          <<: *yarn_cache
      - run: yarn e2e
      - store_artifacts:
          path: dist/cypress/apps/lcexchpro-e2e
          destination: error-screenshots

workflows:
  version: 2
  android_build:
    jobs:
      - install:
          filters:
            branches:
              only: master
      # - check-formatting:
      #     requires:
      #       - install
      - build:
          requires:
            - lint
          filters:
            branches:
              only: master
      